-- =============================================================================
-- RepCheck Database Schema — V8 Score Reasoning & Embedding
-- =============================================================================
-- Adds reasoning and reasoning_embedding to the scores table so the API can
-- serve the current alignment explanation without joining to score_history.
-- Also adds reasoning_embedding to score_history for searchability across
-- the full scoring timeline.
--
-- Design rationale: The scores table is the primary read path for the API.
-- Previously, reasoning lived only in score_history, requiring a join to the
-- latest history row on every page load. Moving reasoning (and its embedding)
-- to scores makes the current explanation self-contained and searchable.
-- History retains its own copy for trend visualization and temporal search.
--
-- Changes:
--   1. scores: add reasoning TEXT and reasoning_embedding vector(1536)
--   2. score_history: add reasoning_embedding vector(1536)
-- =============================================================================

-- ===========================================================================
-- 1. SCORES — Add reasoning and embedding
-- ===========================================================================

ALTER TABLE scores
    ADD COLUMN reasoning TEXT;

ALTER TABLE scores
    ADD COLUMN reasoning_embedding vector(1536);

COMMENT ON COLUMN scores.reasoning IS
    'Current LLM-generated explanation of the alignment score. Overwritten on each re-score. NULL when explanation generation failed or status = no_overlap.';

COMMENT ON COLUMN scores.reasoning_embedding IS
    'Embedding of the current reasoning text for semantic search (e.g., "find legislators where the explanation mentions healthcare"). Generated by DJL/ONNX after scoring. NULL when reasoning is NULL.';

-- HNSW index for reasoning similarity search on current scores
CREATE INDEX idx_scores_reasoning_embedding ON scores
    USING hnsw (reasoning_embedding vector_cosine_ops);

-- ===========================================================================
-- 2. SCORE_HISTORY — Add reasoning embedding
--    reasoning TEXT already exists (added in migration 002).
--    Adding the embedding enables temporal search: "find scoring runs where
--    the explanation mentioned defense spending."
-- ===========================================================================

ALTER TABLE score_history
    ADD COLUMN reasoning_embedding vector(1536);

COMMENT ON COLUMN score_history.reasoning_embedding IS
    'Embedding of the reasoning text at this point in time. Enables temporal semantic search across scoring history.';

-- HNSW index for reasoning similarity search on history
CREATE INDEX idx_score_history_reasoning_embedding ON score_history
    USING hnsw (reasoning_embedding vector_cosine_ops);
